extends RefCounted

# The notices the shipped game carries, shown on the pause menu's LICENCES
# page. The texts below are copied verbatim from the pinned dependencies
# (third_party/README.md): Jolt Physics at e77f1755, godot-cpp at 507ed9d8.
# Godot's own licence and its third-party components come from the engine
# at runtime (Engine.get_license_text, get_copyright_info, get_license_info),
# so they always match the engine the game is built with.

const JOLT_LICENSE := """Copyright 2021 Jorrit Rouwe

Permission is hereby granted, free of charge, to any person obtaining a copy of this software and associated documentation files (the "Software"), to deal in the Software without restriction, including without limitation the rights to use, copy, modify, merge, publish, distribute, sublicense, and/or sell copies of the Software, and to permit persons to whom the Software is furnished to do so, subject to the following conditions:

The above copyright notice and this permission notice shall be included in all copies or substantial portions of the Software.

THE SOFTWARE IS PROVIDED "AS IS", WITHOUT WARRANTY OF ANY KIND, EXPRESS OR IMPLIED, INCLUDING BUT NOT LIMITED TO THE WARRANTIES OF MERCHANTABILITY, FITNESS FOR A PARTICULAR PURPOSE AND NONINFRINGEMENT. IN NO EVENT SHALL THE AUTHORS OR COPYRIGHT HOLDERS BE LIABLE FOR ANY CLAIM, DAMAGES OR OTHER LIABILITY, WHETHER IN AN ACTION OF CONTRACT, TORT OR OTHERWISE, ARISING FROM, OUT OF OR IN CONNECTION WITH THE SOFTWARE OR THE USE OR OTHER DEALINGS IN THE SOFTWARE."""

const GODOT_CPP_LICENSE := """# MIT License

Copyright (c) 2017-present Godot Engine contributors.

Permission is hereby granted, free of charge, to any person obtaining a copy
of this software and associated documentation files (the "Software"), to deal
in the Software without restriction, including without limitation the rights
to use, copy, modify, merge, publish, distribute, sublicense, and/or sell
copies of the Software, and to permit persons to whom the Software is
furnished to do so, subject to the following conditions:

The above copyright notice and this permission notice shall be included in all
copies or substantial portions of the Software.

THE SOFTWARE IS PROVIDED "AS IS", WITHOUT WARRANTY OF ANY KIND, EXPRESS OR
IMPLIED, INCLUDING BUT NOT LIMITED TO THE WARRANTIES OF MERCHANTABILITY,
FITNESS FOR A PARTICULAR PURPOSE AND NONINFRINGEMENT. IN NO EVENT SHALL THE
AUTHORS OR COPYRIGHT HOLDERS BE LIABLE FOR ANY CLAIM, DAMAGES OR OTHER
LIABILITY, WHETHER IN AN ACTION OF CONTRACT, TORT OR OTHERWISE, ARISING FROM,
OUT OF OR IN CONNECTION WITH THE SOFTWARE OR THE USE OR OTHER DEALINGS IN THE
SOFTWARE."""

# As recorded in 00_START_HERE.md (Audio): the clearance of these is release
# plan item 18, open.
const VOICE_NOTE := """The fall voice's 47 lines were generated offline with Chatterbox TTS (MIT), in a voice from Piper en_US-john (LibriVox public-domain recordings). Every other sound, and every texture, is generated by the game's own code."""


static func text() -> String:
	var parts := PackedStringArray()
	parts.append("SCRAPERX uses the following software. Their notices follow.")
	parts.append("GODOT ENGINE\n\n" + Engine.get_license_text())
	parts.append("JOLT PHYSICS\n\n" + JOLT_LICENSE)
	parts.append("GODOT-CPP\n\n" + GODOT_CPP_LICENSE)
	parts.append("SOUND\n\n" + VOICE_NOTE)
	var components := PackedStringArray()
	for component in Engine.get_copyright_info():
		for part in component["parts"]:
			components.append("%s\n%s\nLicence: %s" % [component["name"],
				"\n".join(PackedStringArray(part["copyright"])), part["license"]])
	parts.append("COMPONENTS OF GODOT ENGINE\n\n" + "\n\n".join(components))
	var licences := Engine.get_license_info()
	var names := PackedStringArray(licences.keys())
	names.sort()
	for name in names:
		parts.append("LICENCE: %s\n\n%s" % [name, licences[name]])
	return "\n\n\n".join(parts)
